site_name: Amazon EKS Blueprints Patterns
repo_name: "aws-samples/cdk-eks-blueprints-patterns"
repo_url: "https://github.com/aws-samples/cdk-eks-blueprints-patterns"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Overview: 'index.md'
  - Patterns: 
    - Observability Patterns:
      - Single New EKS AWS Native Observability Pattern: 'https://github.com/aws-observability/cdk-aws-observability-accelerator/blob/main/docs/patterns/single-new-eks-observability-accelerators/single-new-eks-native-observability.md'
      - Single New EKS Opensource Observability Pattern: 'https://github.com/aws-observability/cdk-aws-observability-accelerator/blob/main/docs/patterns/single-new-eks-observability-accelerators/single-new-eks-opensource-observability.md'
      - Multi environment Pipeline GitOps pattern Pattern: 'patterns/pipeline-multi-env-gitops.md'
    - Security Patterns:
      - EKS Config Rules: 'patterns/security/eks-config-rules.md'
      - Encryption At Rest: 'patterns/security/encryption-at-rest.md'
      - GuardDuty: 'patterns/security/guardduty.md'
      - Image Scanning: 'patterns/security/image-scanning.md'
      - SecurityHub: 'patterns/security/securityhub.md'
    - AWS Batch Pattern: 'patterns/batch.md'
    - Customer Network with IPV4 Pattern: 'patterns/custom-networking-with-ipv4.md'
    - Instana Pattern: 'patterns/instana.md'
    - Jupyterhub Pattern: 'patterns/jupyterhub.md'
    - Kubeflow Pattern: 'patterns/kubeflow.md'
    - Multi Account Observability Pattern: 'patterns/multi-account-monitoring.md'
    - Nginx Pattern: 'patterns/nginx.md'
    - Secure Ingress and Authentication Pattern: 'patterns/secureingresscognito.md'
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
plugins:
  - search
